name: konsulmate_new

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  intl: ^0.18.0
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/illustration.png
    - assets/data/dummy.json
    - assets/icons/
    - assets/images/qris.png

  fonts:
    - family: chewy
      fonts:
        - asset: assets/fonts/chewy/Chewy-Regular.ttf