// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVRuIYed3ybGBsYnW82-Bg6sbNg61HS4',
    appId: '1:891293289886:web:127a4715a71d773dfd9a8f',
    messagingSenderId: '891293289886',
    projectId: 'konsulmate-277d1',
    authDomain: 'konsulmate-277d1.firebaseapp.com',
    storageBucket: 'konsulmate-277d1.firebasestorage.app',
    measurementId: 'G-GENP6Q2MLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVpry5fWlwdQG0ym0LMxepGi0K7_7DIgM',
    appId: '1:891293289886:android:26873b0d0196cabffd9a8f',
    messagingSenderId: '891293289886',
    projectId: 'konsulmate-277d1',
    storageBucket: 'konsulmate-277d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3rzCkx_LN6G4Hcgitr7QMzMdNAZl-9s',
    appId: '1:891293289886:ios:da0f80809e25cb37fd9a8f',
    messagingSenderId: '891293289886',
    projectId: 'konsulmate-277d1',
    storageBucket: 'konsulmate-277d1.firebasestorage.app',
    iosBundleId: 'com.example.latihanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb3rzCkx_LN6G4Hcgitr7QMzMdNAZl-9s',
    appId: '1:891293289886:ios:da0f80809e25cb37fd9a8f',
    messagingSenderId: '891293289886',
    projectId: 'konsulmate-277d1',
    storageBucket: 'konsulmate-277d1.firebasestorage.app',
    iosBundleId: 'com.example.latihanFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVRuIYed3ybGBsYnW82-Bg6sbNg61HS4',
    appId: '1:891293289886:web:644879513d064aa0fd9a8f',
    messagingSenderId: '891293289886',
    projectId: 'konsulmate-277d1',
    authDomain: 'konsulmate-277d1.firebaseapp.com',
    storageBucket: 'konsulmate-277d1.firebasestorage.app',
    measurementId: 'G-HV3ZWHXDET',
  );

}